### ISSUE TITLE
Break on first line

### ISSUE THREAD

**Issue by exussum12** [joonty/vdebug#185]
http://stackoverflow.com/questions/3913626/php-netbeans-xdebug-stops-on-every-include-or-require

Netbeans seems to have a fuction which stops on including files. Would it be possible in vdebug ?

**Comment by joonty** [comment]
Hi, [I've asked the author of Xdebug](https://twitter.com/joonty/status/635803230220320769) whether this is possible, and it's clear that Xdebug doesn't support it natively. I imagine that Netbeans sends breakpoints for all files in the project, which works because Netbeans knows exactly which files are included in your project. Since Vim is much more light weight, and has no native concept of projects, this doesn't look like it's going to be possible.

Unless anyone has any bright ideas?

For the time being I'll close this, as I can't think of any way to do it.
