### ISSUE TITLE
break_on_open in MacVim 7.4

### ISSUE THREAD

**Issue by gambledor** [joonty/vdebug#191]
Hi, 
I've the follwing issue.
If I set break_on_open : 0 my MacVim stops to work. I've to press Ctrl-C to stop the debugger and bring vim to life againg.
While If I set break_on_open : 1 it works as expected.

**Comment by joonty** [comment]
Hi @gambledor, sorry for the delay (please see [this post](http://blog.joncairns.com/2015/01/looking-for-another-vdebug-maintainer/) for details).

The reason for this isn't actually a bug. Currently, vdebug is "blocking", which means that you can't use vim when your PHP script is running. You need to set at least one breakpoint, and when the debugger reaches that breakpoint then Vdebug will allow you to inspect the code at that point. It sounds like you have a long-running script that isn't breaking anywhere. 

If you set the break_on_open option to 1, that sets a temporary breakpoint at the start of your script, which is why it works for you in that case.

Try setting a breakpoint at a position where you know that the script should stop. If that doesn't work it sounds like it's a separate issue to do with breakpoints. I'll close this issue for now, but reopen it if you do run in to that.

Thanks
