### ISSUE TITLE
New to this pluing, Vundle didnt find it

### ISSUE THREAD

**Issue by Jzarecta** [joonty/vdebug#203]
I tried to look around if there was already this asked, but I am using vim and vundle, and I am trying to get vdebug through it. However I type :PluginSearch vdebug and receive an empty list. 

This is rather a new install and should be vundle latest version (or a recent one). Please let me know if there is a workaround.

Funny enough I found older project XDebug-DBGp-client-for-PHP

**Comment by joonty** [comment]
Hi,

I didn't actually know that vundle had a search and install feature - that must be new since I last checked. It seems that it uses http://vim-scripts.org/vim/scripts.html, which is meant to be a mirror of http://www.vim.org/scripts/index.php. However, my script is on vim.org ([proof!](http://www.vim.org/scripts/script.php?script_id=4170)]), but not on vim-scripts.org. Conspiracy!

I'd recommend just adding `Bundle 'joonty/vdebug'` to your vimrc - that's probably going to be the easiest way.

Thanks
