### ISSUE TITLE
Getting a second tab/buffer line when debugger is running.

### ISSUE THREAD

**Issue by Yavor-Ivanov** [joonty/vdebug#215]
I'm using [vim-bufferline](https://github.com/bling/vim-bufferline) and have my buffers listed into the statusline like so:
![normal-tabline](https://cloud.githubusercontent.com/assets/5585316/7959123/01065270-09ff-11e5-99c9-6a5b83ce2851.png)

Whenever I run Vdebug, however, I get this extra tab line at the top:
![double-tabline](https://cloud.githubusercontent.com/assets/5585316/7959137/1deb5eee-09ff-11e5-92ba-761baa22ae3f.png)

Is there any way to disable this?

**Comment by joonty** [comment]
Hi,

Vdebug opens everything in a new tab as a way of protecting your current window configuration. I use split screens heavily, and didn't like the way that other plugins would just nuke them down to set up their own config. There was one plugin that tried to put them back the way they were, but it never really worked.

Therefore I made the decision to keep all the new windows in a separate tab, so you can switch back and forth if you want, and when vdebug ends it can cleanly close all of its windows without affecting the original config.

So that's a long way of saying, no, it's not possible to disable it :)

If you want to cycle tabs, you can use `:tabn` and `:tabp`.

Thanks

**Comment by Yavor-Ivanov** [comment]
Thanks for clarifying that, Joonty. The tabline isn't too much of a bother; just something I found curious.

**Comment by joonty** [comment]
Yeh, it's a feature that's not often used. I generally use buffer management too, but in this case it was nice to keep vdebug stuff separate.

Thanks
