### ISSUE TITLE
Code disappears after debug starts

### ISSUE THREAD

**Issue by adamgajzlerowicz** [joonty/vdebug#239]
After I press F5, and refresh the website, everything in  code windows seems to be disappearing. I disabled all plugins, and also tried only in linux terminal mode (no gnome) - with the same result.

Have you got any thoughts on how to fix this please?

![screenshot-4](https://cloud.githubusercontent.com/assets/675615/13797061/83b39b08-eb02-11e5-8a0c-834de0e577cf.png)

**Comment by Dudemullet** [comment]
Are you debugging a remote environment ? This usually happens to me when I debug a remote environment and incorrectly set `g:vdebug_options['path_maps']`. If not, maybe make sure that option isn't set :)

**Comment by adamgajzlerowicz** [comment]
That is exactly what I am doing! Thank you for your help!

**Comment by Dudemullet** [comment]
You're welcome, glad I could help.

**Comment by BlackIkeEagle** [comment]
@adamgajzlerowicz so this was fixed ?

**Comment by cincodenada** [comment]
@adamgajzlerowicz To clarify what's going on here, for understanding: debugging opens a new tab that shows whatever file is currently being executed in the left window, and various status windows on the right.  The files you were editing are intact in their own tab.

Since your pathmaps weren't set up correctly, Vdebug tried to open the file on your computer using the remote path, and didn't find anything, hence the blank window.  You can see it's trying to open `/var/www/html/debug.php`, which seems to not exist on your local machine.

**Comment by cincodenada** [comment]
Closing, as it seems the issue has been resolved, and there has been no response for a week.  @adamgajzlerowicz if you're still having this issue, feel free to comment and we will re-open.
